name: 'build docker image'
description: 'build docker image'

# 定義輸入的參數
inputs:
  # docker hub 的 id
  docker_hub_user:
    description: 'docker hub user'
    required: true
  # docker hub 的 token
  docker_hub_token:
    description: 'docker hub token'
    required: true
  # image 名稱
  image_name:
    description: 'docker image name'
    required: true

runs:
  using: "composite"
  steps:
    - name: docker login
      run: |
        echo ${{ inputs.docker_hub_token }} > password.txt
        cat password.txt | docker login --username ${{ inputs.docker_hub_user }} --password-stdin
      shell: bash
    - name: build image
      run: |
        docker image build -t ${{ inputs.docker_hub_user }}/${{ inputs.image_name }} .
      shell: bash
    - name: push image
      run: |
        docker image push ${{ inputs.docker_hub_user }}/${{ inputs.image_name }}
      shell: bash